version: "3.7"
services:
  postgres:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: opendatacubepassword
    restart: always

  #  localstack:
  #    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
  #    image: localstack/localstack
  #    # network_mode: bridge
  #    ports:
  #      - "4566:4566"
  #    environment:
  #      - SERVICES=s3
  #      - DEBUG=1

  stats:
    image: opendatacube/datacube-statistician:0.3.9
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=datacube
      - AWS_NO_SIGN_REQUEST=true
      - STAC_API_URL=https://earth-search.aws.element84.com/v0/
    restart: always
    depends_on:
      - postgres
    #      - localstack
    command: tail -f /dev/null
    volumes:
      - ./:/code/
