---
urls:
  slope: https://deafrica-data.s3.amazonaws.com/ancillary/dem-derivatives/cog_slope_africa.tif
  model: https://github.com/digitalearthafrica/crop-mask/blob/main/testing/eastern_cropmask/results/gm_mads_two_seasons_ml_model_20210427.joblib?raw=true
  chirps:
    - s3://deafrica-input-datasets/rainfall/CHPclim_jan_jun_cumulative_rainfall.tif
    - s3://deafrica-input-datasets/rainfall/CHPclim_jul_dec_cumulative_rainfall.tif
  wdpa: s3://deafrica-input-datasets/protected_areas/WDPA_eastern.tif
  aez: https://github.com/digitalearthafrica/crop-mask/blob/main/testing/eastern_cropmask/data/Eastern.geojson?raw=true
  td: https://github.com/digitalearthafrica/crop-mask/blob/main/testing/eastern_cropmask/results/training_data/gm_mads_two_seasons_training_data_20210427.txt?raw=true

rename_dict:
  B02: blue
  B03: green
  B04: red
  B05: red_edge_1
  B06: red_edge_2
  B07: red_edge_3
  B08: nir
  B11: swir_1
  B12: swir_2
  BCMAD: bcdev
  EMAD: edev
  SMAD: sdev
