plugin: pred-gm-s2
max_processing_time: 3600
job_queue_max_lease: 900
renew_safety_margin: 60
future_poll_interval: 2
s3_acl: bucket-ownder-full-control
# Generic product attributes
cog_opts:
  zlevel: 4
  overrides:
    rgba:
      compress: JPEG
      jpeg_quality: 90
product:
  name: crop_mask_eastern
  short_name: crop_mask_eastern
  version: 1.0.0
  product_family: geomedian
  collections_site: explorer.digitalearth.africa
  producer: digitalearthafrica.org
  region_code_format: "x{x:03d}y{y:03d}"
# computing resources
threads: 31
memory_limit: 240Gi
# sample of dependent data and sqs name
# filedb: s3://deafrica-data-dev-af/crop_mask_eastern/0-1-0/gm_s2_semiannual_all.db
# from_sqs: deafrica-dev-eks-stats-geomedian-semiannual
