name : Crop-mask Push

on:
  push:
    branches:
      - main
    paths:
      - 'docker/version.txt'
      - '.github/workflows/cropmask-push.yml'

env:
  IMAGE_NAME: digitalearthafrica/crop-mask

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get tag for this build if it exists
      run: |
        echo "VERSION=$(cat docker/version.txt)" >> $GITHUB_ENV

    - name: Build and Push unstable Docker Image from PR / Push to Master
      uses: whoan/docker-build-with-cache-action@v4
      with:
        image_name: ${{ env.IMAGE_NAME }}
        username: gadockersvc
        password: ${{ secrets.GADOCKERSVC_PASSWORD }}
        image_tag: latest,${{ env.VERSION }}
